import {
  SETTINGS_KEY, DEFAULT_SETTINGS,
  AUTO_TRADES_KEY, AUTO_CLOSED_KEY, AUTO_TRADES_TS_KEY,
  TRADES_KEY, WATCHLIST_KEY, ALERTS_KEY, SIGHIST_KEY,
} from "../constants.js";

export function loadSettings() {
  try { const r = localStorage.getItem(SETTINGS_KEY); return r ? { ...DEFAULT_SETTINGS, ...JSON.parse(r) } : { ...DEFAULT_SETTINGS }; } catch { return { ...DEFAULT_SETTINGS }; }
}

export function saveSettings(s) {
  try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(s)); } catch {}
}

// ═══════════ 自動推薦單（系統自動掃描+建單+監控） ═══════════════════════════

export function loadAutoTrades() {
  try {
    const raw = localStorage.getItem(AUTO_TRADES_KEY);
    return raw ? JSON.parse(raw) : { longs: [], shorts: [] };
  } catch { return { longs: [], shorts: [] }; }
}

export function saveAutoTrades(data) {
  try { localStorage.setItem(AUTO_TRADES_KEY, JSON.stringify(data)); } catch {}
}

export function loadClosedTrades() {
  try {
    const raw = localStorage.getItem(AUTO_CLOSED_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

export function saveClosedTrades(arr) {
  try { localStorage.setItem(AUTO_CLOSED_KEY, JSON.stringify(arr)); } catch {}
}

// 日誌同步：只在新單加入時執行（不是每次 closed 陣列變都跑）

export function syncNewClosedToJournal(newlyClosed) {
  if (!newlyClosed || newlyClosed.length === 0) return;
  try {
    const journal = JSON.parse(localStorage.getItem(TRADES_KEY) || "[]");
    const existingIds = new Set(journal.map((j) => j.id));
    let added = false;
    newlyClosed.forEach((t) => {
      if (!existingIds.has(t.id) && t.exitReason) {
        journal.push({
          id: t.id,
          symbol: t.symbol,
          name: t.name,
          direction: t.direction === "long" ? "做多" : "做空",
          entry: t.entry,
          exitPrice: t.exitPrice,
          pnl: (t.pnlPct ?? 0).toFixed(2),
          rMultiple: t.rMultiple != null ? t.rMultiple.toFixed(2) : "—",
          reason: t.exitReason,
          ts: t.closedTs,
          status: "closed",
          autoGenerated: true,
        });
        added = true;
      }
    });
    if (added) localStorage.setItem(TRADES_KEY, JSON.stringify(journal));
  } catch {}
}

export export function loadAutoTradesTs() {
  try { return parseInt(localStorage.getItem(AUTO_TRADES_TS_KEY) || "0", 10); } catch { return 0; }
}

export export function saveAutoTradesTs(ts) {
  try { localStorage.setItem(AUTO_TRADES_TS_KEY, String(ts)); } catch {}
}


export function loadTrades() {
  try {
    const raw = localStorage.getItem(TRADES_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

export function saveTrades(trades) {
  try { localStorage.setItem(TRADES_KEY, JSON.stringify(trades)); } catch {}
}


export function loadWatchlist() {
  try { const r = localStorage.getItem(WATCHLIST_KEY); return r ? JSON.parse(r) : []; } catch { return []; }
}

export function saveWatchlist(arr) {
  try { localStorage.setItem(WATCHLIST_KEY, JSON.stringify(arr)); } catch {}
}

// ═══════════ 到價提醒 storage ═══════════════════════════════════════════════

export function loadPriceAlerts() {
  try { const r = localStorage.getItem(ALERTS_KEY); return r ? JSON.parse(r) : []; } catch { return []; }
}

export function savePriceAlerts(arr) {
  try { localStorage.setItem(ALERTS_KEY, JSON.stringify(arr)); } catch {}
}

// ═══════════ 持倉風險總覽 ═══════════════════════════════════════════════════

export function loadSigHistory() {
  try { const r = localStorage.getItem(SIGHIST_KEY); return r ? JSON.parse(r) : {}; } catch { return {}; }
}

export function saveSigHistory(h) {
  try { localStorage.setItem(SIGHIST_KEY, JSON.stringify(h)); } catch {}
}

// ═══════════ 市場總覽儀表板 ═══════════════════════════════════════════════════
